### ISSUE TITLE
Warning levels too high

### ISSUE THREAD

**Issue by RainerWinkler** [kmetz/coro2sens#1]
Hi Mr Metz, 
Thanks for building and sharing:-)
The recommended level for the red light during the COVID-19 pandemic I am aware of is 1000 ppm. You may check this.
See also my blog where I collected the understanding I have currently on this https://medium.com/@rainer.winkler.poaceae/recommendations-for-use-of-co2-sensors-to-control-room-air-quality-during-the-covid-19-pandemic-c04cac6644d0
Best regards,
Rainer

**Comment by kmetz** [comment]
Hi Rainer, thank you for reporting this! I will read the documents an will propably adjust the levels (and make them configurable more easily). Your medium article seems to be a great reference, thanks for that.

**Comment by kmetz** [comment]
I made thresholds configurable in code and changed defaults to 800/1000 ppm for yellow/red. The old 1000/2000 values are still mentioned in code.

**Comment by RainerWinkler** [comment]
Hi Kaspar, 
thanks! 
Best regards and success with you project!
Rainer
